### ISSUE TITLE
Terminals in grammar are tokens?

### ISSUE THREAD

**Issue by Noise47** [colonelmo/cod-box-pI#1]
So we have variable and terminal for our grammar.Are these terminals tokens or there are exceptions?

**Comment by colonelmo** [comment]
They are indeed tokens and the classes representing them  could also be Tokens but that would introduce some coupling. later on the tokens could be given too much functionality (functionality that for example scanner would not make any use of) if we proceed with this mind set. I believe it would be better if some wrapper around tokens represented terminals.
